source:
  url: "https://img.cdn.cratecode.com/info/headerimg/julia-set.1vrz.webp?format=auto&width=3840"

config:
  output:
    path: "./output/output"
    num: 100

mode: bytes

defaults:
  chunksize: 14000000

mutations:
  # - expand:
      # by: {"min": 2, "max": 20 }
  - reverse: {}
  # - accelerate:
  #     from: 0
  #     by: {"min": 1, "max": 10}
  #     after: {"min": 50000, "max": 400000}
  # - multiply:
  #     by: {"min": 2, "max": 10}

# chains:
#   - mutations:
#       compress:
#         by: 2
#         # by: {"min": 2, "max": 5}
#       multiply:
#         by: 0.9
#   - mutations:
#       shift:
#         by: 200
  