source:
  url: "https://science.nasa.gov/wp-content/uploads/2023/09/Carina_Nebula-1.jpeg"

config:
  output:
    path: "./output/output"
    num: 100

mode: bytes

defaults:
  chunksize: 4000000

mutations:
  # - expand:
      # by: {"min": 2, "max": 20 }
  # - reverse: {}
  # - accelerate:
  #     from: 0
  #     by: {"min": 1, "max": 10}
  #     after: {"min": 100, "max": 100000}
  # - multiply:
  #     by: {"min": 1, "max": 1.3}
  - compress:
      by: {"min": 1, "max": 5}
  - expand:
      by: {"min": 1, "max": 5}
  # - reverse:
  #     {}
  # - shift:
  #     by:
  #       - 1
  #       - 10
  #       - 100
  # - increment:
  #     by: {"min": 1, "max": 100}

# chains:
#   - mutations:
#       compress:
#         by: 2
#         # by: {"min": 2, "max": 5}
#       multiply:
#         by: 0.9
#   - mutations:
#       shift:
#         by: 200
  