source:
  url: "https://static.wikia.nocookie.net/limbuscompany/images/6/6e/Dante_StandingSprite.png"

config:
  output:
    path: "./output/output"
    extension: "jpeg"
    num: 100

mode: bytes

defaults:
  chunksize: 3000000
  # chunksize:
  #   bytes: 4_000_000
  #   percentage: 0.8

features:
  # This will pre-convert the image you pass in as the format specified.
  # LIMITATIONS: Source must be an image. Only valid formats allowed.
  # NOTE: Will overwrite the extension by whatever the format provided is.
  #
  # not implemented...
  #
  # default: disabled
  pre-convert:
    format: tiff
  
  # This will duplicate the source as local files immediately and modify
  # said files in memory - which might be faster.
  #
  # default: false
  memory-map: true

  # Executes mutations in parallel.
  # NOTE: Currently unsupported.
  #
  # not implemented...
  #
  # default: disabled
  parallel: false

  # Mutates the same file on every iteration, saving each iteration as its
  # own file. If false, it will use a copy of the file for each iteration.
  #
  # LIMITATIONS: [parallel] isn't supported if this is enabled, since being
  # sequential requires that the mutations be done in order.
  #
  # default: false
  sequential: true

mutations:
  # - expand:
      # by: {"min": 2, "max": 20 }
  # - reverse: {}
  # - accelerate:
  #     from: 0
  #     by: {"min": 1, "max": 10}
  #     after: {"min": 100, "max": 100000}
  - multiply:
      by: {"min": 0.5, "max": 2}
  # - compress:
  #     by:
  #       min: 1
  #       max: 5
  # - expand:
  #     by:
  #       min: 1
  #       max: 5
  # - reverse:
  #     {}
  # - shift:
  #     by:
  #       - 1
  #       - 10
  #       - 100
  #       - 1000
  # - increment:
  #     by: {"min": 1, "max": 100}

# chains:
#   - mutations:
#       compress:
#         by: 2
#         # by: {"min": 2, "max": 5}
#       multiply:
#         by: 0.9
#   - mutations:
#       shift:
#         by: 200
  