source:
  url: "https://science.nasa.gov/wp-content/uploads/2023/09/Carina_Nebula-1.jpeg"

config:
  output:
    path: "./output/output"
    extension: "jpeg"
    num: 100

mode: bytes

defaults:
  chunksize: 4000000
  # chunksize:
  #   bytes: 4_000_000
  #   percentage: 0.8

features:
  # This will pre-convert the image you pass in as the format specified.
  # LIMITATIONS: Source must be an image. Only valid formats allowed.
  # NOTE: Will overwrite the extension by whatever the format provided is.
  pre-convert:
    format: tiff
  
  # This will duplicate the source as local files immediately and modify
  # said files in memory - which should be significantly faster.
  #
  # Should likely be always enabled unless bugs are encountered.
  memory-map: true

  # Executes mutations in parallel.
  # NOTE: Currently unsupported.
  parallel: false

  # Mutates the same file on every iteration, saving each iteration as its
  # own file. If false, it will use a copy of the file for each iteration.
  #
  # LIMITATIONS: [parallel] isn't supported if this is enabled, since being
  # sequential requires that the mutations be done in order.
  sequential: true

mutations:
  # - expand:
      # by: {"min": 2, "max": 20 }
  # - reverse: {}
  # - accelerate:
  #     from: 0
  #     by: {"min": 1, "max": 10}
  #     after: {"min": 100, "max": 100000}
  # - multiply:
  #     by: {"min": 1, "max": 1.3}
  - compress:
      by:
        min: 1
        max: 5
  - expand:
      by:
        min: 1
        max: 5
  # - reverse:
  #     {}
  # - shift:
  #     by:
  #       - 1
  #       - 10
  #       - 100
  # - increment:
  #     by: {"min": 1, "max": 100}

# chains:
#   - mutations:
#       compress:
#         by: 2
#         # by: {"min": 2, "max": 5}
#       multiply:
#         by: 0.9
#   - mutations:
#       shift:
#         by: 200
  