# Specifies the file to mutate. Will be used, not modified.
inputfile = "input/niko.tif"

# Can be omitted
# Specifies the output file
outputfile = "output/kino.tif"

# How many times to execute the application
times = 300

# How many times to perform the mutations in a row
iterations = [1,5]

# Size of each chunk to mutate at a time
chunksize = [19300,193000]

# Available mutations:
# Void, Chaos, Loops, Reverse,
# Shift, Shuffle, Swap
# Increase, Gradient, Multiply
# Compress
mutations = [
	["Compress"],
	["Multiply"],
	["Reverse"],
	["Shift"],
	["Shift", "Multiply", "Reverse"],
	["Void"],
	["Chaos"],
	["Swap"]
]

# Additional options for special mutations.
# If more options are required, the application should inform you of what to do.
[LoopsConfig]
loops = 20
chunksize = 1_00_000

[IncreaseConfig]
increaseby = [1,255]

[GradientConfig]
accelerateby = [1,2]
acceleratein = [10_000, 100_000]

[MultiplyConfig]
multiplyby = [0.5,1.5]

# You can override options for mutations.
# Just use <MutationName>Config.
[ShiftConfig]
iterations = [100,1000]
chunksize = [1,10]

[CompressConfig]
compressby = 2
