# Specifies the file to mutate. Will be used, not modified.
inputfile = "somedumbvid.avi"

# Can be omitted
# Specifies the output file
outputfile = "output/hands.avi"

# How many times to execute the application
times = 10

# How many times to perform the mutations in a row
iterations = [1,10]

# Size of each chunk to mutate at a time
chunksize = [100_000_000,1_000_000_000]

# Available mutations:
# Void, Chaos, Loops, Reverse,
# Shift, Shuffle, Swap
# Increase, Gradient
mutations = [
    ["Shift", "Gradient", "Swap"],
	["Swap", "Gradient", "Increase"],
	["Chaos", "Void", "Shift"]
]

# Additional options for special mutations.
# If more options are required, the application should inform you of what to do.
[LoopConfig]
loops = [10]

[IncreaseConfig]
increase_by = [1,255]

[GradientConfig]
accelerate_by = [1,2]
accelerate_in = [1_000_000, 10_000_000]

# You can override options for mutations.
# Just use <MutationName>Config.
# [ShiftConfig]
# iterations = [3,5]
# chunksize = [100,1000]
