# Specifies the file to mutate. Will be used, not modified.
inputfile = "input/input.avi"

# Can be omitted
# Specifies the output file
outputfile = "output/output.avi"

# How many times to execute the application
times = 100

# How many times to perform the mutations in a row
iterations = [1_000]

# Size of each chunk to mutate at a time
chunksize = [5000]

# Available mutations:
# Void, Chaos, Loops, Reverse,
# Shift, Shuffle, Swap
# Increase, Gradient, Multiply
# Compress
mutations = [
	# ["Compress"],
	#["Multiply", "Shift"],
	# ["Reverse"],
	# ["Shift"],
	# ["Void"],
	["Chaos"],
	#["Swap"],
	#["Loops"],
	# ["Shuffle"],
	#["Increase"],
	#["Gradient"]
]

# Additional options for special mutations.
# If more options are required, the application should inform you of what to do.
[LoopsConfig]
loops = [20]
chunksize = [700_000]

[IncreaseConfig]
increase_by = [1,5]

[GradientConfig]
accelerate_by = [1,2]
accelerate_in = [10_000, 100_000]

[MultiplyConfig]
multiply_by = [0.9]

# You can override options for mutations.
# Just use <MutationName>Config.
[ShiftConfig]
iterations = [1,1000]
chunksize = [1]

[CompressConfig]
compress_by = [2]
