inputfile = "input/cactus.tif"
outputfile = "output/cactus.tif"
times = 1
iterations = [1005]
chunksize = [50000]
# Available mutations:
# Void, Chaos, Loops, Reverse,
# Shift, Shuffle, Swap
# Increase, Gradient
mutations = [
    ["Reverse", "Swap", "Increase", "Gradient"],
    ["Shuffle", "Chaos"],
    ["Shift"]
]

[LoopConfig]
loops = [10]

[IncreaseConfig]
increase_by = [1,255]

[GradientConfig]
accelerate_by = [1,2]
accelerate_in = [100_000, 5_000_000]

[ShiftConfig]
iterations = [10]
chunksize = [5000]