# Specifies the file to mutate. Will be used, not modified.
inputfile = "test.rs"

# Can be omitted
# Specifies the output file
outputfile = "die.rs"

# How many times to execute the application
times = 1

# How many times to perform the mutations in a row
iterations = [1000]

# Size of each chunk to mutate at a time
chunksize = [100]

# Available mutations:
# Void, Chaos, Loops, Reverse,
# Shift, Shuffle, Swap
# Increase, Gradient
mutations = [
    ["Void", "Chaos"],
    ["Void", "Chaos", "Void"],
    ["Void", "Void"],
    ["Reverse"]
]

# Additional options for special mutations.
# If more options are required, the application should inform you of what to do.
[LoopConfig]
loops = [10]

[IncreaseConfig]
increase_by = [1,255]

[GradientConfig]
accelerate_by = [1,2]
accelerate_in = [100_000, 5_000_000]

# You can override options for mutations.
# Just use <MutationName>Config.
[ShiftConfig]
iterations = [10]
chunksize = [5000]
