# Specifies the file to mutate. Will be used, not modified.
inputfile = "input/OMINOUS.tif"

# Can be omitted
# Specifies the output file
outputfile = "output/OMINOUS.tif"

# How many times to execute the application
times = 40

# How many times to perform the mutations in a row
iterations = [1,5]

# Size of each chunk to mutate at a time
chunksize = [700000,7000000]

# Available mutations:
# Void, Chaos, Loops, Reverse,
# Shift, Shuffle, Swap
# Increase, Gradient, Multiply
# Compress
mutations = [
	#["Compress"],
	#["Multiply"],
	#["Reverse"],
	#["Shift"],
	#["Void"],
	#["Chaos"],
	["Swap"],
	["Loops"],
	#["Shuffle"],
	#["Increase"],
	["Gradient"]
]

# Additional options for special mutations.
# If more options are required, the application should inform you of what to do.
[LoopConfig]
loops = [20]
chunksize = [7_00_000]

[IncreaseConfig]
increase_by = [1,5]

[GradientConfig]
accelerate_by = [1,2]
accelerate_in = [10_000, 100_000]

[MultiplyConfig]
multiply_by = [0.5]

# You can override options for mutations.
# Just use <MutationName>Config.
[ShiftConfig]
iterations = [1,1000]
chunksize = [1,10]

[CompressConfig]
compress_by = [2]
