inputfile = "input/cactus.tif"
outputfile = "output/cactus.tif"
times = 5
iterations = [1]
chunksize = [5, 10]
# Available mutations:
# Void, Chaos, Loops, Reverse,
# Shift, Shuffle, Swap
# Increase, Gradient
mutations = [
    ["Loops", "Reverse", "Swap", "Increase", "Gradient"],
    ["Shuffle", "Chaos"],
    ["Shift"]
]

[LoopConfig]
loops = [1,1000]

[IncreaseConfig]
increase_by = [1,255]

[GradientConfig]
accelerate_by = [1,2]
accelerate_in = [100_000, 5_000_000]